apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    role: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      role: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: zambrano1997/frontend
        ports:
        - containerPort: 80