
# FROM node:16 as build

# WORKDIR /usr/local/app
# COPY ./ /usr/local/app/

# RUN npm install

# USER root

# EXPOSE 80


FROM node:16 as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
CMD ["npm", "start"]