apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  matchLabels:
    role: backend
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
    metadata:
      labels:
        role: backend
    spec:
      containers:
        - name: backend
          image: zambrano1997/backend
          ports:
        - containerPort: 5000
