apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    role: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      role: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
      - name: backend
        image: zambrano1997/backend
        ports:
        - containerPort: 5000
